services:

  postgres:
    image: postgres:17
    container_name: recoverai-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: recoverai
      POSTGRES_DB: recoverai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend

    container_name: recoverai-backend

    env_file:
      - ./backend/.env

    environment:
      DATABASE_URL: postgresql://postgres:recoverai@postgres:5432/recoverai

    ports:
      - "8000:8000"

    depends_on:
      - postgres


  frontend:
    build:
      context: ./frontend

    container_name: recoverai-frontend

    environment:
      VITE_API_URL: http://localhost:8000

    ports:
      - "5173:5173"

    depends_on:
      - backend


volumes:
  postgres_data: